# Site settings
title: "Xiao Liu Resume"
description: "A resume template for Xiao Liu and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Xiao Liu"
resume_title:                   "PHD Applicant Resume"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "xiaoliu1990@cs.umass.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1-4132753041"
resume_contact_address:         "College of Information and Computer Sciences, University of Massachusetts Amherst"

resume_header_contact_info:     "College of Information and Computer Sciences, University of Massachusetts Amherst • +1-4132753041 • xiaoliu1990@cs.umass.edu"
display_header_contact_info:    "true"

resume_header_intro1: "<p>I am a first-year master student in College of Information and Computer Sciences at the University of Massachusetts Amherst, advised by Professor. "
resume_header_intro2: "My research interests are Computer Vision ,Machine Learning and Graph Neural Networks. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_research:        true
resume_section_publications:    true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true

resume_section_experience:      true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/johnsmith2012"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://johnsmith2012.github.io/resume/"
  # resume_medium_url:            "zljabroad@outlook.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
